version: "3.8"

services:
  proxy-server:
    build:
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    privileged: true
    tty: true

  server:
    build:
      dockerfile: ./docker/server.Dockerfile
    volumes:
      - dht11-log:/app/packages/log/dht11
    
  dht11:
    build:
      dockerfile: ./docker/dht11.Dockerfile
    volumes:
      - dht11-log:/app/log
    privileged: true
    tty: true

volumes:
  dht11-log:
    external: true
