version: "3.8"

services:
  proxy-server:
    build:
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    privileged: true
    tty: true

  server:
    build:
      dockerfile: ./docker/server.Dockerfile
